plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
}



allprojects{
	group = 'com.criscahub'
	version = '0.0.1-SNAPSHOT'

	repositories {
		mavenCentral()
	}
}

subprojects {
	apply plugin:'java'
	apply plugin:'io.spring.dependency-management'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(21)
		}
	}

	dependencyManagement {
		imports {
			mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
		}
	}

	dependencies {

		compileOnly 'org.projectlombok:lombok:1.18.42'
		annotationProcessor 'org.projectlombok:lombok:1.18.42'

		//Mapstruct
		// Source: https://mvnrepository.com/artifact/org.projectlombok/lombok-mapstruct-binding
		implementation("org.projectlombok:lombok-mapstruct-binding:0.2.0")

		// Source: https://mvnrepository.com/artifact/org.mapstruct/mapstruct
		implementation("org.mapstruct:mapstruct:1.6.3")

		// Source: https://mvnrepository.com/artifact/org.mapstruct/mapstruct-processor
		annotationProcessor("org.mapstruct:mapstruct-processor:1.6.3")

		//Binding lombok-mapstruct
		// Source: https://mvnrepository.com/artifact/org.projectlombok/lombok-mapstruct-binding
		implementation("org.projectlombok:lombok-mapstruct-binding:0.2.0")

		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

		//Javax validation
		implementation("org.springframework.boot:spring-boot-starter-validation")


		implementation 'org.springframework.boot:spring-boot-starter-security'
		implementation 'org.springframework.security:spring-security-oauth2-authorization-server'
		implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

	}

	tasks.named('test') {
		useJUnitPlatform()
	}

}


